### ISSUE TITLE
v0.4.0 Now requires (2) additional dependencies "@aws-cdk/aws-lambda-nodejs" and "@aws-cdk/aws-lambda-python"

### ISSUE THREAD

**Issue by mystical44** [DataDog/datadog-cdk-constructs#59]
## Expected Behavior
Clean build after upgrading to v0.4.0

## Actual Behavior
Migrating from v0.3.0 to v0.4.0 results in a breaking change.  Previously, my project did not require "@aws-cdk/aws-lambda-nodejs" and "@aws-cdk/aws-lambda-python" (which I do not use anyway), but after upgrading to v0.4.0, I get:

`node_modules/datadog-cdk-constructs/lib/datadog.d.ts(2,31): error TS2307: Cannot find module '@aws-cdk/aws-lambda-nodejs' or its corresponding type declarations.
node_modules/datadog-cdk-constructs/lib/datadog.d.ts(3,31): error TS2307: Cannot find module '@aws-cdk/aws-lambda-python' or its corresponding type declarations.`

## Steps to Reproduce the Problem

  1. Starting with a project with v0.3.0 and without the mentioned dependencies, upgrade to v0.4.0 and perform a new build

## Specifications

  - Datadog Lambda Layer version: 9
  - Node version: 62
  
## Stacktrace
  
  ```
`node_modules/datadog-cdk-constructs/lib/datadog.d.ts(2,31): error TS2307: Cannot find module '@aws-cdk/aws-lambda-nodejs' or its corresponding type declarations.
node_modules/datadog-cdk-constructs/lib/datadog.d.ts(3,31): error TS2307: Cannot find module '@aws-cdk/aws-lambda-python' or its corresponding type declarations.`
  ```

**Comment by mystical44** [comment]
tsconfig.json

`{
  "compilerOptions": {
    "outDir": "dist",
    "target":"ES2018",
    "module": "commonjs",
    "lib": ["es2018"],
    "declaration": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization":false,
    "typeRoots": ["./node_modules/@types"]
  },
  "include": ["lib", "bin", "lambdas"]
}
`

**Comment by gsdwait** [comment]
We use this construct library inside another construct library and we're seeing the same issue when we try to update to 0.4.0.

**Comment by nhinsch** [comment]
Hi @mystical44 and @gsdwait, thanks for submitting this issue. You are correct that version `0.4.0` changes the library's peer dependencies, and is therefore considered a breaking change. I have updated the release notes to reflect this. However, because the version number of this library is less than 1.0.0, the API is considered unstable and breaking changes are possible without incrementing the major version.

Are the new peer dependencies inhibiting your workflow in some way?

**Comment by nhinsch** [comment]
Also, does updating to the latest version of CDK resolve the issue for you?

**Comment by mystical44** [comment]
Hey @nhinsch , I am on @aws-cdk/core `1.118.0` atm.  The new dependencies don't inhibit my flow **now** that I am aware, but my builds were originally breaking.  Also, adding unnecessary dependencies is obviously not ideal..

**Comment by nhinsch** [comment]
Thanks for the clarification!

The new peer dependencies were added so that this library can now support some additional types of constructs from AWS that provide alternative ways of packaging and deploying functions. Not everyone will use all of these constructs in their stacks, but we wanted to support as many different workflows as possible with our library.

I am going to close this issue for now but if this change is causing problems, or if you think there is something we should be doing differently with regard to our support for the `NodejsFunction` and `PythonFunction` constructs, please do let us know.

**Comment by mystical44** [comment]
Just a future note to whoever reads this thread that this **wasn't** fixed. Rather it is assumed that users will add these (2) dependencies to their apps, otherwise it will break your builds!

**Comment by dani-mp** [comment]
I just had to add `@aws-cdk/aws-lambda-python-alpha` to my SST project (node) to make TypeScript happy. It felt weird, is there anything I'm missing?
